baseURL = 'https://heroes.youthsteaminitiative.org/'
languageCode = 'en-us'
title = 'Illuminate Heritage: Lightscapes of Lexington'
theme = 'ananke'
copyright = "<a href='https://youthsteaminitiative.org' class='f4 fw4 white-70 hover-white no-underline tc'>©Youth STEAM Initiative 2026</a>"

[params]
  mainSections = []

[params.ananke.social.follow]
  networks = ["youtube", "instagram", "facebook", "email"]

[params.ananke.social.youtube]
  profilelink = "https://www.youtube.com/@YouthSTEAMInitiative"

[params.ananke.social.instagram]
  profilelink = "https://www.instagram.com/youth.steam.initiative/"

[params.ananke.social.facebook]
  profilelink = "https://www.facebook.com/people/Youth-STEAM-Initiative/61569154958515/"

[params.ananke.social.email]
  profilelink = "mailto:lyst.connect@gmail.com"
[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About Us"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Sponsors"
  url = "/sponsors/"
  weight = 3